### ISSUE TITLE
My phone's qrcode app can't scan any of the default cli output…?

### ISSUE THREAD

**Issue by iarna** [watilde/qrip#1]
I'm using [Barcode Scanner](https://play.google.com/store/apps/details?id=com.google.zxing.client.android&hl=en) on Android. This includes all three output modes.

The coloration also seems to be inverted to me (with a dark background terminal—I suspect it'd look fine with a light colored background).

It's probably also worth noting that the emoji versions don't align correctly if you're using Unicode 9 character sizing. (As of Unicode 9, emoji are officially full-width.) I don't know that there's anything you can do about this… you can't detect which Unicode version the terminal implements. Maybe a flag on the CLI?

(By contrast, qrcode-terminal works fine for me, but it gets solid squares by changing the background color. This also lets it have consistent coloration regardless of your selection of dark or light background for your terminal.)

**Comment by watilde** [comment]
Oh yeah, I can imagine that `#` doesn't work as QA code. I will refactor the codes which were created 3 years ago :laughing:. Will remove the emoji version as well, it was maybe just a joke to write an article.

Thanks for your feedback!

**Comment by watilde** [comment]
Updated the symbol and shipped as `v2.0.2`. I confirmed that the Barcode Scanner could scan the generated QA code.

Closing as resolved.
