### ISSUE TITLE
Unable to generate QR code for strings with exclamation mark

### ISSUE THREAD

**Issue by reinhart1010** [watilde/qrip#2]
Doing so will give an error, e.g.
> bash: !long-url`: event not found

**Comment by rbottomley** [comment]
Use quotes:

qrip "Bob was here!"

![qrip](https://user-images.githubusercontent.com/12174341/43986597-333c5960-9cc8-11e8-89c8-4cb8b92fc91e.png)

**Comment by watilde** [comment]
Yes, we need to quote string if it contains spaces. Closing as resolved, but let me know if it does not resolve your issue.

Thank you!
